name : test_wf1
on: push
jobs: 
    arka1:
        runs-on: ubuntu-latest
        steps:
            - name: get code
              uses: actions/checkout@v4
            - name: install dependencies
              run: npm ci
            - name: run Lint
              run : npm run lint
            - name: run tests
              run: |
                echo "running tests"
                npm test
            - name: Build
              run : npm run build
            - name: Run Deploy
              run : echo "Deploying...."



