name : test_wf1
on: push
jobs: 
    Test:
        runs-on: ubuntu-latest
        steps:
            - name: get code
              uses: actions/checkout@v4
            - name: install dependencies
              run: npm ci
            - name: run Lint
              run : npm run lint
            - name: run Test
              run: npm run test
    Build:
        needs: Test
        runs-on: ubuntu-latest
        outputs: 
          JSfilename : ${{ steps.publish.outputs.filename}}
        steps:
            - name: get code
              uses: actions/checkout@v4
            - name: install dependencies
              run: npm ci
            - name: Build
              run : npm run build
            - name: list JS files
              id: publish
              run: find dist/asstes/*.js -type f -exec echo 'filename={}' >> $GITHUB_OUTPUT \;
            - name : upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: my_artifact
                path: |
                  dist
                  package.json
    Deploy:
        needs: Build
        runs-on: ubuntu-latest
        steps:
           - name: Run Deploy
             run : echo "Deploying...."
           - name: Download artifacts
             uses: actions/download-artifact@v4
             with:
              name: my_artifact
           - name: Output Contents
             run: ls



